import 'dart:convert';
import 'dart:io';

/// Builds `lib/l10n/tr_<code>.dart` from JSON files in `tool/translations/`.
///
/// Each JSON file is an object mapping the exact English key (as listed in
/// `tool/l10n_keys.txt`) to its translation. A language is only written when it
/// covers every key with no extras, so partial/duplicate work is rejected.
const Map<String, String> _langs = {
  'ti': 'kTi',
  'gez': 'kGez',
  'om': 'kOm',
  'so': 'kSo',
  'aa': 'kAa',
  'sid': 'kSid',
  'wal': 'kWal',
  'hdy': 'kHdy',
  'gmv': 'kGmv',
  'gru': 'kGru',
  'stv': 'kStv',
  'har': 'kHar',
};

void main() {
  final keysFile = File('tool/l10n_keys.txt');
  final keys = keysFile
      .readAsLinesSync()
      .map((l) => l.replaceAll(r'\n', '\n'))
      .where((l) => l.isNotEmpty)
      .toList();
  final keySet = keys.toSet();
  stdout.writeln('expecting ${keys.length} keys per language');

  for (final entry in _langs.entries) {
    final file = File('tool/translations/${entry.key}.json');
    if (!file.existsSync()) {
      stdout.writeln('${entry.key}: SKIP (no ${file.path})');
      continue;
    }
    final decoded = jsonDecode(file.readAsStringSync());
    if (decoded is! Map) {
      stdout.writeln('${entry.key}: SKIP (not a JSON object)');
      continue;
    }
    final map = <String, String>{};
    var badValue = false;
    decoded.forEach((k, v) {
      if (k is! String || v is! String || v.trim().isEmpty) {
        badValue = true;
      } else {
        map[k] = v;
      }
    });
    final missing = keySet.where((k) => !map.containsKey(k)).toList();
    final extra = map.keys.where((k) => !keySet.contains(k)).toList();
    if (badValue || missing.isNotEmpty || extra.isNotEmpty) {
      stdout.writeln(
        '${entry.key}: SKIP (bad=$badValue, missing=${missing.length}, '
        'extra=${extra.length})',
      );
      for (final m in missing.take(8)) {
        stdout.writeln('   missing: $m');
      }
      for (final x in extra.take(8)) {
        stdout.writeln('   extra: $x');
      }
      continue;
    }

    final sorted = map.keys.toList()..sort();
    final buf = StringBuffer()
      ..writeln('// Generated by tool/build_dicts.dart. Do not edit by hand.')
      ..writeln('const Map<String, String> ${entry.value} = {');
    for (final k in sorted) {
      buf.writeln('  ${_dart(k)}: ${_dart(map[k]!)},');
    }
    buf.writeln('};');
    File(
      'lib/l10n/tr_${entry.key}.dart',
    ).writeAsStringSync(buf.toString(), encoding: utf8);
    stdout.writeln('${entry.key}: wrote ${map.length} entries');
  }
}

String _dart(String value) {
  final buf = StringBuffer();
  for (final rune in value.runes) {
    final ch = String.fromCharCode(rune);
    if (ch == r'\') {
      buf.write(r'\\');
    } else if (ch == "'") {
      buf.write(r"\'");
    } else if (ch == r'$') {
      buf.write(r'\$');
    } else if (ch == '\n') {
      buf.write(r'\n');
    } else if (ch == '\r') {
      buf.write(r'\r');
    } else if (ch == '\t') {
      buf.write(r'\t');
    } else {
      buf.write(ch);
    }
  }
  return "'$buf'";
}
